name: Weather GitActions

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps: 
    - uses: actions/checkout@v3
    - name: Set ip Python
      uses: actions/setup-python@3v
      with: 
        python-version: '3.9.5'
    - name: Install python packages
      run: 
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests
    - name: Execute py script
      run: python weather.py
    - uses: stefanzweifel/git-auto-commit-action@v4